import { Manrope } from "next/font/google";
import Navbar from "@/components/Navbar";
import { cn } from '@/lib/utils'
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Prueba Técnica Modal | Harold Pineda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn('relative h-full font-sans antialiased', manrope.className)}>
        <main className="relative flex flex-col min-h-screen">
        <Navbar></Navbar>
           {children}
        </main>
      </body>
    </html>
  );
}
